#!/bin/bash

mkdir 002
mv frame_002.zip 002/
cd 002/
unzip frame_002.zip
rm frame_002.zip
cd ..

mkdir 003
mv frame_003.zip 003/
cd 003/
unzip frame_003.zip
rm frame_003.zip
cd ..

mkdir 004
mv frame_004_split.zip 004/
mv frame_004_split.z01 004/
mv frame_004_split.z02 004/
cd 004/
zip frame_004_split.zip -s=0 --out frame_004.zip
unzip frame_004.zip
rm frame_004.zip
rm frame_004_split.zip
rm frame_004_split.z01
rm frame_004_split.z02
cd ..

mkdir 010
mv frame_010.zip 010/
cd 010/
unzip frame_010.zip
rm frame_010.zip
cd ..

mkdir 011
mv frame_011.zip 011/
cd 011/
unzip frame_011.zip
rm frame_011.zip
cd ..

mkdir 013
mv frame_013_split.zip 013/
mv frame_013_split.z01 013/
mv frame_013_split.z02 013/
cd 013/
zip frame_013_split.zip -s=0 --out frame_013.zip
unzip frame_013.zip
rm frame_013.zip
rm frame_013_split.zip
rm frame_013_split.z01
rm frame_013_split.z02
cd ..

mkdir 014
mv frame_014_split.zip 014/
mv frame_014_split.z01 014/
mv frame_014_split.z02 014/
cd 014/
zip frame_014_split.zip -s=0 --out frame_014.zip
unzip frame_014.zip
rm frame_014.zip
rm frame_014_split.zip
rm frame_014_split.z01
rm frame_014_split.z02
cd ..

mkdir 016
mv frame_016.zip 016/
cd 016/
unzip frame_016.zip
rm frame_016.zip
cd ..

mkdir 017
mv frame_017.zip 017/
cd 017/
unzip frame_017.zip
rm frame_017.zip
cd ..

mkdir 018
mv frame_018.zip 018/
cd 018/
unzip frame_018.zip
rm frame_018.zip
cd ..

mkdir 019
mv frame_019.zip 019/
cd 019/
unzip frame_019.zip
rm frame_019.zip
cd ..

mkdir 020
mv frame_020.zip 020/
cd 020/
unzip frame_020.zip
rm frame_020.zip
cd ..

mkdir 021
mv frame_021.zip 021/
cd 021/
unzip frame_021.zip
rm frame_021.zip
cd ..

mkdir 023
mv frame_023.zip 023/
cd 023/
unzip frame_023.zip
rm frame_023.zip
cd ..

mkdir 024
mv frame_024.zip 024/
cd 024/
unzip frame_024.zip
rm frame_024.zip
cd ..

mkdir 025
mv frame_025.zip 025/
cd 025/
unzip frame_025.zip
rm frame_025.zip
cd ..

mkdir 026
mv frame_026.zip 026/
cd 026/
unzip frame_026.zip
rm frame_026.zip
cd ..

mkdir 028
mv frame_028.zip 028/
cd 028/
unzip frame_028.zip
rm frame_028.zip
cd ..

mkdir 030
mv frame_030.zip 030/
cd 030/
unzip frame_030.zip
rm frame_030.zip
cd ..

mkdir 031
mv frame_031_split.zip 031/
mv frame_031_split.z01 031/
mv frame_031_split.z02 031/
cd 031/
zip frame_031_split.zip -s=0 --out frame_031.zip
unzip frame_031.zip
rm frame_031.zip
rm frame_031_split.zip
rm frame_031_split.z01
rm frame_031_split.z02
cd ..

mkdir 032
mv frame_032_split.zip 032/
mv frame_032_split.z01 032/
mv frame_032_split.z02 032/
cd 032/
zip frame_032_split.zip -s=0 --out frame_032.zip
unzip frame_032.zip
rm frame_032.zip
rm frame_032_split.zip
rm frame_032_split.z01
rm frame_032_split.z02
cd ..

mkdir 034
mv frame_034.zip 034/
cd 034/
unzip frame_034.zip
rm frame_034.zip
cd ..

mkdir 035
mv frame_035.zip 035/
cd 035/
unzip frame_035.zip
rm frame_035.zip
cd ..

mkdir 037
mv frame_037.zip 037/
cd 037/
unzip frame_037.zip
rm frame_037.zip
cd ..

mkdir 039
mv frame_039.zip 039/
cd 039/
unzip frame_039.zip
rm frame_039.zip
cd ..

mkdir 043
mv frame_043_split.zip 043/
mv frame_043_split.z01 043/
cd 043/
zip frame_043_split.zip -s=0 --out frame_043.zip
unzip frame_043.zip
rm frame_043.zip
rm frame_043_split.zip
rm frame_043_split.z01
cd ..

mkdir 044
mv frame_044.zip 044/
cd 044/
unzip frame_044.zip
rm frame_044.zip
cd ..

mkdir 046
mv frame_046.zip 046/
cd 046/
unzip frame_046.zip
rm frame_046.zip
cd ..

mkdir 047
mv frame_047.zip 047/
cd 047/
unzip frame_047.zip
rm frame_047.zip
cd ..

mkdir 048
mv frame_048.zip 048/
cd 048/
unzip frame_048.zip
rm frame_048.zip
cd ..

mkdir 049
mv frame_049.zip 049/
cd 049/
unzip frame_049.zip
rm frame_049.zip
cd ..

mkdir 050
mv frame_050.zip 050/
cd 050/
unzip frame_050.zip
rm frame_050.zip
cd ..

mkdir 051
mv frame_051.zip 051/
cd 051/
unzip frame_051.zip
rm frame_051.zip
cd ..

mkdir 053
mv frame_053.zip 053/
cd 053/
unzip frame_053.zip
rm frame_053.zip
cd ..

mkdir 054
mv frame_054.zip 054/
cd 054/
unzip frame_054.zip
rm frame_054.zip
cd ..

mkdir 055
mv frame_055.zip 055/
cd 055/
unzip frame_055.zip
rm frame_055.zip
cd ..

mkdir 056
mv frame_056.zip 056/
cd 056/
unzip frame_056.zip
rm frame_056.zip
cd ..

mkdir 057
mv frame_057.zip 057/
cd 057/
unzip frame_057.zip
rm frame_057.zip
cd ..

mkdir 058
mv frame_058.zip 058/
cd 058/
unzip frame_058.zip
rm frame_058.zip
cd ..

mkdir 060
mv frame_060.zip 060/
cd 060/
unzip frame_060.zip
rm frame_060.zip
cd ..

mkdir 062
mv frame_062.zip 062/
cd 062/
unzip frame_062.zip
rm frame_062.zip
cd ..

mkdir 063
mv frame_063.zip 063/
cd 063/
unzip frame_063.zip
rm frame_063.zip
cd ..

mkdir 064
mv frame_064.zip 064/
cd 064/
unzip frame_064.zip
rm frame_064.zip
cd ..

mkdir 065
mv frame_065.zip 065/
cd 065/
unzip frame_065.zip
rm frame_065.zip
cd ..

mkdir 066
mv frame_066.zip 066/
cd 066/
unzip frame_066.zip
rm frame_066.zip
cd ..

mkdir 067
mv frame_067.zip 067/
cd 067/
unzip frame_067.zip
rm frame_067.zip
cd ..

mkdir 068
mv frame_068.zip 068/
cd 068/
unzip frame_068.zip
rm frame_068.zip
cd ..

mkdir 069
mv frame_069.zip 069/
cd 069/
unzip frame_069.zip
rm frame_069.zip
cd ..

mkdir 070
mv frame_070.zip 070/
cd 070/
unzip frame_070.zip
rm frame_070.zip
cd ..

mkdir 071
mv frame_071.zip 071/
cd 071/
unzip frame_071.zip
rm frame_071.zip
cd ..

mkdir 072
mv frame_072.zip 072/
cd 072/
unzip frame_072.zip
rm frame_072.zip
cd ..

mkdir 075
mv frame_075.zip 075/
cd 075/
unzip frame_075.zip
rm frame_075.zip
cd ..

mkdir 076
mv frame_076.zip 076/
cd 076/
unzip frame_076.zip
rm frame_076.zip
cd ..

mkdir 078
mv frame_078.zip 078/
cd 078/
unzip frame_078.zip
rm frame_078.zip
cd ..

mkdir 080
mv frame_080.zip 080/
cd 080/
unzip frame_080.zip
rm frame_080.zip
cd ..

mkdir 081
mv frame_081.zip 081/
cd 081/
unzip frame_081.zip
rm frame_081.zip
cd ..

mkdir 082
mv frame_082.zip 082/
cd 082/
unzip frame_082.zip
rm frame_082.zip
cd ..

mkdir 084
mv frame_084.zip 084/
cd 084/
unzip frame_084.zip
rm frame_084.zip
cd ..

mkdir 085
mv frame_085.zip 085/
cd 085/
unzip frame_085.zip
rm frame_085.zip
cd ..

mkdir 088
mv frame_088.zip 088/
cd 088/
unzip frame_088.zip
rm frame_088.zip
cd ..

mkdir 090
mv frame_090.zip 090/
cd 090/
unzip frame_090.zip
rm frame_090.zip
cd ..

mkdir 091
mv frame_091_split.zip 091/
mv frame_091_split.z01 091/
cd 091/
zip frame_091_split.zip -s=0 --out frame_091.zip
unzip frame_091.zip
rm frame_091.zip
rm frame_091_split.zip
rm frame_091_split.z01
cd ..

mkdir 094
mv frame_094.zip 094/
cd 094/
unzip frame_094.zip
rm frame_094.zip
cd ..

mkdir 097
mv frame_097_split.zip 097/
mv frame_097_split.z01 097/
cd 097/
zip frame_097_split.zip -s=0 --out frame_097.zip
unzip frame_097.zip
rm frame_097.zip
rm frame_097_split.zip
rm frame_097_split.z01
cd ..

mkdir 098
mv frame_098.zip 098/
cd 098/
unzip frame_098.zip
rm frame_098.zip
cd ..

mkdir 099
mv frame_099.zip 099/
cd 099/
unzip frame_099.zip
rm frame_099.zip
cd ..

mkdir 100
mv frame_100.zip 100/
cd 100/
unzip frame_100.zip
rm frame_100.zip
cd ..

mkdir 101
mv frame_101.zip 101/
cd 101/
unzip frame_101.zip
rm frame_101.zip
cd ..

mkdir 103
mv frame_103.zip 103/
cd 103/
unzip frame_103.zip
rm frame_103.zip
cd ..

mkdir 104
mv frame_104.zip 104/
cd 104/
unzip frame_104.zip
rm frame_104.zip
cd ..

mkdir 105
mv frame_105.zip 105/
cd 105/
unzip frame_105.zip
rm frame_105.zip
cd ..

mkdir 108
mv frame_108.zip 108/
cd 108/
unzip frame_108.zip
rm frame_108.zip
cd ..

mkdir 109
mv frame_109_split.zip 109/
mv frame_109_split.z01 109/
mv frame_109_split.z02 109/
cd 109/
zip frame_109_split.zip -s=0 --out frame_109.zip
unzip frame_109.zip
rm frame_109.zip
rm frame_109_split.zip
rm frame_109_split.z01
rm frame_109_split.z02
cd ..

mkdir 110
mv frame_110.zip 110/
cd 110/
unzip frame_110.zip
rm frame_110.zip
cd ..

mkdir 113
mv frame_113_split.zip 113/
mv frame_113_split.z01 113/
mv frame_113_split.z02 113/
cd 113/
zip frame_113_split.zip -s=0 --out frame_113.zip
unzip frame_113.zip
rm frame_113.zip
rm frame_113_split.zip
rm frame_113_split.z01
rm frame_113_split.z02
cd ..

mkdir 116
mv frame_116.zip 116/
cd 116/
unzip frame_116.zip
rm frame_116.zip
cd ..

mkdir 118
mv frame_118_split.zip 118/
mv frame_118_split.z01 118/
mv frame_118_split.z02 118/
cd 118/
zip frame_118_split.zip -s=0 --out frame_118.zip
unzip frame_118.zip
rm frame_118.zip
rm frame_118_split.zip
rm frame_118_split.z01
rm frame_118_split.z02
cd ..

mkdir 119
mv frame_119.zip 119/
cd 119/
unzip frame_119.zip
rm frame_119.zip
cd ..

mkdir 120
mv frame_120.zip 120/
cd 120/
unzip frame_120.zip
rm frame_120.zip
cd ..

mkdir 123
mv frame_123.zip 123/
cd 123/
unzip frame_123.zip
rm frame_123.zip
cd ..

mkdir 126
mv frame_126.zip 126/
cd 126/
unzip frame_126.zip
rm frame_126.zip
cd ..

mkdir 127
mv frame_127.zip 127/
cd 127/
unzip frame_127.zip
rm frame_127.zip
cd ..

mkdir 128
mv frame_128.zip 128/
cd 128/
unzip frame_128.zip
rm frame_128.zip
cd ..

mkdir 129
mv frame_129.zip 129/
cd 129/
unzip frame_129.zip
rm frame_129.zip
cd ..

mkdir 130
mv frame_130.zip 130/
cd 130/
unzip frame_130.zip
rm frame_130.zip
cd ..

mkdir 131
mv frame_131.zip 131/
cd 131/
unzip frame_131.zip
rm frame_131.zip
cd ..

mkdir 132
mv frame_132.zip 132/
cd 132/
unzip frame_132.zip
rm frame_132.zip
cd ..

mkdir 133
mv frame_133_split.zip 133/
mv frame_133_split.z01 133/
cd 133/
zip frame_133_split.zip -s=0 --out frame_133.zip
unzip frame_133.zip
rm frame_133.zip
rm frame_133_split.zip
rm frame_133_split.z01
cd ..

mkdir 134
mv frame_134.zip 134/
cd 134/
unzip frame_134.zip
rm frame_134.zip
cd ..

mkdir 135
mv frame_135.zip 135/
cd 135/
unzip frame_135.zip
rm frame_135.zip
cd ..

mkdir 136
mv frame_136.zip 136/
cd 136/
unzip frame_136.zip
rm frame_136.zip
cd ..

mkdir 137
mv frame_137.zip 137/
cd 137/
unzip frame_137.zip
rm frame_137.zip
cd ..

mkdir 138
mv frame_138.zip 138/
cd 138/
unzip frame_138.zip
rm frame_138.zip
cd ..

mkdir 139
mv frame_139_split.zip 139/
mv frame_139_split.z01 139/
cd 139/
zip frame_139_split.zip -s=0 --out frame_139.zip
unzip frame_139.zip
rm frame_139.zip
rm frame_139_split.zip
rm frame_139_split.z01
cd ..

mkdir 140
mv frame_140.zip 140/
cd 140/
unzip frame_140.zip
rm frame_140.zip
cd ..

mkdir 142
mv frame_142.zip 142/
cd 142/
unzip frame_142.zip
rm frame_142.zip
cd ..

mkdir 145
mv frame_145.zip 145/
cd 145/
unzip frame_145.zip
rm frame_145.zip
cd ..

mkdir 146
mv frame_146.zip 146/
cd 146/
unzip frame_146.zip
rm frame_146.zip
cd ..

mkdir 147
mv frame_147_split.zip 147/
mv frame_147_split.z01 147/
cd 147/
zip frame_147_split.zip -s=0 --out frame_147.zip
unzip frame_147.zip
rm frame_147.zip
rm frame_147_split.zip
rm frame_147_split.z01
cd ..

mkdir 149
mv frame_149_split.zip 149/
mv frame_149_split.z01 149/
cd 149/
zip frame_149_split.zip -s=0 --out frame_149.zip
unzip frame_149.zip
rm frame_149.zip
rm frame_149_split.zip
rm frame_149_split.z01
cd ..

mkdir 150
mv frame_150_split.zip 150/
mv frame_150_split.z01 150/
cd 150/
zip frame_150_split.zip -s=0 --out frame_150.zip
unzip frame_150.zip
rm frame_150.zip
rm frame_150_split.zip
rm frame_150_split.z01
cd ..

mkdir 152
mv frame_152.zip 152/
cd 152/
unzip frame_152.zip
rm frame_152.zip
cd ..

mkdir 154
mv frame_154_split.zip 154/
mv frame_154_split.z01 154/
mv frame_154_split.z02 154/
cd 154/
zip frame_154_split.zip -s=0 --out frame_154.zip
unzip frame_154.zip
rm frame_154.zip
rm frame_154_split.zip
rm frame_154_split.z01
rm frame_154_split.z02
cd ..

mkdir 158
mv frame_158_split.zip 158/
mv frame_158_split.z01 158/
cd 158/
zip frame_158_split.zip -s=0 --out frame_158.zip
unzip frame_158.zip
rm frame_158.zip
rm frame_158_split.zip
rm frame_158_split.z01
cd ..

mkdir 161
mv frame_161.zip 161/
cd 161/
unzip frame_161.zip
rm frame_161.zip
cd ..

mkdir 162
mv frame_162.zip 162/
cd 162/
unzip frame_162.zip
rm frame_162.zip
cd ..

mkdir 164
mv frame_164.zip 164/
cd 164/
unzip frame_164.zip
rm frame_164.zip
cd ..

mkdir 165
mv frame_165.zip 165/
cd 165/
unzip frame_165.zip
rm frame_165.zip
cd ..

mkdir 167
mv frame_167_split.zip 167/
mv frame_167_split.z01 167/
mv frame_167_split.z02 167/
cd 167/
zip frame_167_split.zip -s=0 --out frame_167.zip
unzip frame_167.zip
rm frame_167.zip
rm frame_167_split.zip
rm frame_167_split.z01
rm frame_167_split.z02
cd ..

mkdir 168
mv frame_168.zip 168/
cd 168/
unzip frame_168.zip
rm frame_168.zip
cd ..

mkdir 169
mv frame_169_split.zip 169/
mv frame_169_split.z01 169/
cd 169/
zip frame_169_split.zip -s=0 --out frame_169.zip
unzip frame_169.zip
rm frame_169.zip
rm frame_169_split.zip
rm frame_169_split.z01
cd ..

mkdir 170
mv frame_170.zip 170/
cd 170/
unzip frame_170.zip
rm frame_170.zip
cd ..

mkdir 171
mv frame_171.zip 171/
cd 171/
unzip frame_171.zip
rm frame_171.zip
cd ..

mkdir 174
mv frame_174.zip 174/
cd 174/
unzip frame_174.zip
rm frame_174.zip
cd ..

mkdir 175
mv frame_175_split.zip 175/
mv frame_175_split.z01 175/
cd 175/
zip frame_175_split.zip -s=0 --out frame_175.zip
unzip frame_175.zip
rm frame_175.zip
rm frame_175_split.zip
rm frame_175_split.z01
cd ..

mkdir 177
mv frame_177.zip 177/
cd 177/
unzip frame_177.zip
rm frame_177.zip
cd ..

mkdir 178
mv frame_178.zip 178/
cd 178/
unzip frame_178.zip
rm frame_178.zip
cd ..

mkdir 179
mv frame_179.zip 179/
cd 179/
unzip frame_179.zip
rm frame_179.zip
cd ..

mkdir 180
mv frame_180_split.zip 180/
mv frame_180_split.z01 180/
cd 180/
zip frame_180_split.zip -s=0 --out frame_180.zip
unzip frame_180.zip
rm frame_180.zip
rm frame_180_split.zip
rm frame_180_split.z01
cd ..

mkdir 182
mv frame_182.zip 182/
cd 182/
unzip frame_182.zip
rm frame_182.zip
cd ..

mkdir 184
mv frame_184.zip 184/
cd 184/
unzip frame_184.zip
rm frame_184.zip
cd ..

mkdir 185
mv frame_185.zip 185/
cd 185/
unzip frame_185.zip
rm frame_185.zip
cd ..

mkdir 186
mv frame_186.zip 186/
cd 186/
unzip frame_186.zip
rm frame_186.zip
cd ..

mkdir 187
mv frame_187_split.zip 187/
mv frame_187_split.z01 187/
cd 187/
zip frame_187_split.zip -s=0 --out frame_187.zip
unzip frame_187.zip
rm frame_187.zip
rm frame_187_split.zip
rm frame_187_split.z01
cd ..

mkdir 189
mv frame_189.zip 189/
cd 189/
unzip frame_189.zip
rm frame_189.zip
cd ..

mkdir 191
mv frame_191_split.zip 191/
mv frame_191_split.z01 191/
cd 191/
zip frame_191_split.zip -s=0 --out frame_191.zip
unzip frame_191.zip
rm frame_191.zip
rm frame_191_split.zip
rm frame_191_split.z01
cd ..

mkdir 192
mv frame_192.zip 192/
cd 192/
unzip frame_192.zip
rm frame_192.zip
cd ..

mkdir 193
mv frame_193.zip 193/
cd 193/
unzip frame_193.zip
rm frame_193.zip
cd ..

mkdir 194
mv frame_194_split.zip 194/
mv frame_194_split.z01 194/
cd 194/
zip frame_194_split.zip -s=0 --out frame_194.zip
unzip frame_194.zip
rm frame_194.zip
rm frame_194_split.zip
rm frame_194_split.z01
cd ..

mkdir 195
mv frame_195.zip 195/
cd 195/
unzip frame_195.zip
rm frame_195.zip
cd ..

mkdir 197
mv frame_197_split.zip 197/
mv frame_197_split.z01 197/
mv frame_197_split.z02 197/
mv frame_197_split.z03 197/
mv frame_197_split.z04 197/
mv frame_197_split.z05 197/
mv frame_197_split.z06 197/
cd 197/
zip frame_197_split.zip -s=0 --out frame_197.zip
unzip frame_197.zip
rm frame_197.zip
rm frame_197_split.zip
rm frame_197_split.z01
rm frame_197_split.z02
rm frame_197_split.z03
rm frame_197_split.z04
rm frame_197_split.z05
rm frame_197_split.z06
cd ..

mkdir 198
mv frame_198.zip 198/
cd 198/
unzip frame_198.zip
rm frame_198.zip
cd ..

mkdir 199
mv frame_199_split.zip 199/
mv frame_199_split.z01 199/
mv frame_199_split.z02 199/
cd 199/
zip frame_199_split.zip -s=0 --out frame_199.zip
unzip frame_199.zip
rm frame_199.zip
rm frame_199_split.zip
rm frame_199_split.z01
rm frame_199_split.z02
cd ..

mkdir 200
mv frame_200.zip 200/
cd 200/
unzip frame_200.zip
rm frame_200.zip
cd ..

mkdir 202
mv frame_202_split.zip 202/
mv frame_202_split.z01 202/
cd 202/
zip frame_202_split.zip -s=0 --out frame_202.zip
unzip frame_202.zip
rm frame_202.zip
rm frame_202_split.zip
rm frame_202_split.z01
cd ..

mkdir 203
mv frame_203.zip 203/
cd 203/
unzip frame_203.zip
rm frame_203.zip
cd ..

mkdir 205
mv frame_205_split.zip 205/
mv frame_205_split.z01 205/
mv frame_205_split.z02 205/
mv frame_205_split.z03 205/
mv frame_205_split.z04 205/
cd 205/
zip frame_205_split.zip -s=0 --out frame_205.zip
unzip frame_205.zip
rm frame_205.zip
rm frame_205_split.zip
rm frame_205_split.z01
rm frame_205_split.z02
rm frame_205_split.z03
rm frame_205_split.z04
cd ..

mkdir 206
mv frame_206.zip 206/
cd 206/
unzip frame_206.zip
rm frame_206.zip
cd ..

mkdir 207
mv frame_207.zip 207/
cd 207/
unzip frame_207.zip
rm frame_207.zip
cd ..

mkdir 208
mv frame_208_split.zip 208/
mv frame_208_split.z01 208/
mv frame_208_split.z02 208/
cd 208/
zip frame_208_split.zip -s=0 --out frame_208.zip
unzip frame_208.zip
rm frame_208.zip
rm frame_208_split.zip
rm frame_208_split.z01
rm frame_208_split.z02
cd ..

mkdir 210
mv frame_210_split.zip 210/
mv frame_210_split.z01 210/
mv frame_210_split.z02 210/
cd 210/
zip frame_210_split.zip -s=0 --out frame_210.zip
unzip frame_210.zip
rm frame_210.zip
rm frame_210_split.zip
rm frame_210_split.z01
rm frame_210_split.z02
cd ..

mkdir 211
mv frame_211_split.zip 211/
mv frame_211_split.z01 211/
mv frame_211_split.z02 211/
cd 211/
zip frame_211_split.zip -s=0 --out frame_211.zip
unzip frame_211.zip
rm frame_211.zip
rm frame_211_split.zip
rm frame_211_split.z01
rm frame_211_split.z02
cd ..

mkdir 213
mv frame_213.zip 213/
cd 213/
unzip frame_213.zip
rm frame_213.zip
cd ..

mkdir 214
mv frame_214_split.zip 214/
mv frame_214_split.z01 214/
cd 214/
zip frame_214_split.zip -s=0 --out frame_214.zip
unzip frame_214.zip
rm frame_214.zip
rm frame_214_split.zip
rm frame_214_split.z01
cd ..

mkdir 216
mv frame_216_split.zip 216/
mv frame_216_split.z01 216/
mv frame_216_split.z02 216/
mv frame_216_split.z03 216/
cd 216/
zip frame_216_split.zip -s=0 --out frame_216.zip
unzip frame_216.zip
rm frame_216.zip
rm frame_216_split.zip
rm frame_216_split.z01
rm frame_216_split.z02
rm frame_216_split.z03
cd ..

mkdir 218
mv frame_218.zip 218/
cd 218/
unzip frame_218.zip
rm frame_218.zip
cd ..

mkdir 219
mv frame_219.zip 219/
cd 219/
unzip frame_219.zip
rm frame_219.zip
cd ..

mkdir 220
mv frame_220.zip 220/
cd 220/
unzip frame_220.zip
rm frame_220.zip
cd ..

mkdir 221
mv frame_221.zip 221/
cd 221/
unzip frame_221.zip
rm frame_221.zip
cd ..

mkdir 222
mv frame_222_split.zip 222/
mv frame_222_split.z01 222/
cd 222/
zip frame_222_split.zip -s=0 --out frame_222.zip
unzip frame_222.zip
rm frame_222.zip
rm frame_222_split.zip
rm frame_222_split.z01
cd ..

mkdir 223
mv frame_223_split.zip 223/
mv frame_223_split.z01 223/
cd 223/
zip frame_223_split.zip -s=0 --out frame_223.zip
unzip frame_223.zip
rm frame_223.zip
rm frame_223_split.zip
rm frame_223_split.z01
cd ..

mkdir 225
mv frame_225.zip 225/
cd 225/
unzip frame_225.zip
rm frame_225.zip
cd ..

mkdir 227
mv frame_227.zip 227/
cd 227/
unzip frame_227.zip
rm frame_227.zip
cd ..

mkdir 228
mv frame_228.zip 228/
cd 228/
unzip frame_228.zip
rm frame_228.zip
cd ..

mkdir 231
mv frame_231_split.zip 231/
mv frame_231_split.z01 231/
mv frame_231_split.z02 231/
mv frame_231_split.z03 231/
mv frame_231_split.z04 231/
mv frame_231_split.z05 231/
mv frame_231_split.z06 231/
cd 231/
zip frame_231_split.zip -s=0 --out frame_231.zip
unzip frame_231.zip
rm frame_231.zip
rm frame_231_split.zip
rm frame_231_split.z01
rm frame_231_split.z02
rm frame_231_split.z03
rm frame_231_split.z04
rm frame_231_split.z05
rm frame_231_split.z06
cd ..

mkdir 232
mv frame_232.zip 232/
cd 232/
unzip frame_232.zip
rm frame_232.zip
cd ..

mkdir 233
mv frame_233.zip 233/
cd 233/
unzip frame_233.zip
rm frame_233.zip
cd ..

mkdir 235
mv frame_235_split.zip 235/
mv frame_235_split.z01 235/
cd 235/
zip frame_235_split.zip -s=0 --out frame_235.zip
unzip frame_235.zip
rm frame_235.zip
rm frame_235_split.zip
rm frame_235_split.z01
cd ..

mkdir 236
mv frame_236.zip 236/
cd 236/
unzip frame_236.zip
rm frame_236.zip
cd ..

mkdir 237
mv frame_237.zip 237/
cd 237/
unzip frame_237.zip
rm frame_237.zip
cd ..

mkdir 238
mv frame_238.zip 238/
cd 238/
unzip frame_238.zip
rm frame_238.zip
cd ..

mkdir 239
mv frame_239.zip 239/
cd 239/
unzip frame_239.zip
rm frame_239.zip
cd ..

mkdir 240
mv frame_240_split.zip 240/
mv frame_240_split.z01 240/
cd 240/
zip frame_240_split.zip -s=0 --out frame_240.zip
unzip frame_240.zip
rm frame_240.zip
rm frame_240_split.zip
rm frame_240_split.z01
cd ..

mkdir 241
mv frame_241.zip 241/
cd 241/
unzip frame_241.zip
rm frame_241.zip
cd ..

mkdir 242
mv frame_242.zip 242/
cd 242/
unzip frame_242.zip
rm frame_242.zip
cd ..

mkdir 243
mv frame_243_split.zip 243/
mv frame_243_split.z01 243/
cd 243/
zip frame_243_split.zip -s=0 --out frame_243.zip
unzip frame_243.zip
rm frame_243.zip
rm frame_243_split.zip
rm frame_243_split.z01
cd ..

mkdir 245
mv frame_245.zip 245/
cd 245/
unzip frame_245.zip
rm frame_245.zip
cd ..

mkdir 246
mv frame_246.zip 246/
cd 246/
unzip frame_246.zip
rm frame_246.zip
cd ..

mkdir 247
mv frame_247.zip 247/
cd 247/
unzip frame_247.zip
rm frame_247.zip
cd ..

mkdir 248
mv frame_248.zip 248/
cd 248/
unzip frame_248.zip
rm frame_248.zip
cd ..

mkdir 249
mv frame_249.zip 249/
cd 249/
unzip frame_249.zip
rm frame_249.zip
cd ..

mkdir 250
mv frame_250.zip 250/
cd 250/
unzip frame_250.zip
rm frame_250.zip
cd ..

mkdir 251
mv frame_251.zip 251/
cd 251/
unzip frame_251.zip
rm frame_251.zip
cd ..

mkdir 252
mv frame_252.zip 252/
cd 252/
unzip frame_252.zip
rm frame_252.zip
cd ..

mkdir 253
mv frame_253.zip 253/
cd 253/
unzip frame_253.zip
rm frame_253.zip
cd ..

mkdir 254
mv frame_254.zip 254/
cd 254/
unzip frame_254.zip
rm frame_254.zip
cd ..

mkdir 257
mv frame_257.zip 257/
cd 257/
unzip frame_257.zip
rm frame_257.zip
cd ..

mkdir 260
mv frame_260_split.zip 260/
mv frame_260_split.z01 260/
cd 260/
zip frame_260_split.zip -s=0 --out frame_260.zip
unzip frame_260.zip
rm frame_260.zip
rm frame_260_split.zip
rm frame_260_split.z01
cd ..

mkdir 262
mv frame_262_split.zip 262/
mv frame_262_split.z01 262/
cd 262/
zip frame_262_split.zip -s=0 --out frame_262.zip
unzip frame_262.zip
rm frame_262.zip
rm frame_262_split.zip
rm frame_262_split.z01
cd ..

mkdir 263
mv frame_263_split.zip 263/
mv frame_263_split.z01 263/
mv frame_263_split.z02 263/
cd 263/
zip frame_263_split.zip -s=0 --out frame_263.zip
unzip frame_263.zip
rm frame_263.zip
rm frame_263_split.zip
rm frame_263_split.z01
rm frame_263_split.z02
cd ..

mkdir 264
mv frame_264.zip 264/
cd 264/
unzip frame_264.zip
rm frame_264.zip
cd ..

mkdir 265
mv frame_265_split.zip 265/
mv frame_265_split.z01 265/
mv frame_265_split.z02 265/
cd 265/
zip frame_265_split.zip -s=0 --out frame_265.zip
unzip frame_265.zip
rm frame_265.zip
rm frame_265_split.zip
rm frame_265_split.z01
rm frame_265_split.z02
cd ..

mkdir 266
mv frame_266.zip 266/
cd 266/
unzip frame_266.zip
rm frame_266.zip
cd ..

mkdir 267
mv frame_267.zip 267/
cd 267/
unzip frame_267.zip
rm frame_267.zip
cd ..

mkdir 269
mv frame_269.zip 269/
cd 269/
unzip frame_269.zip
rm frame_269.zip
cd ..

mkdir 271
mv frame_271.zip 271/
cd 271/
unzip frame_271.zip
rm frame_271.zip
cd ..

mkdir 272
mv frame_272_split.zip 272/
mv frame_272_split.z01 272/
cd 272/
zip frame_272_split.zip -s=0 --out frame_272.zip
unzip frame_272.zip
rm frame_272.zip
rm frame_272_split.zip
rm frame_272_split.z01
cd ..

mkdir 276
mv frame_276.zip 276/
cd 276/
unzip frame_276.zip
rm frame_276.zip
cd ..

mkdir 278
mv frame_278.zip 278/
cd 278/
unzip frame_278.zip
rm frame_278.zip
cd ..

mkdir 279
mv frame_279.zip 279/
cd 279/
unzip frame_279.zip
rm frame_279.zip
cd ..

mkdir 280
mv frame_280.zip 280/
cd 280/
unzip frame_280.zip
rm frame_280.zip
cd ..

mkdir 281
mv frame_281.zip 281/
cd 281/
unzip frame_281.zip
rm frame_281.zip
cd ..

mkdir 282
mv frame_282.zip 282/
cd 282/
unzip frame_282.zip
rm frame_282.zip
cd ..

mkdir 283
mv frame_283.zip 283/
cd 283/
unzip frame_283.zip
rm frame_283.zip
cd ..

mkdir 284
mv frame_284.zip 284/
cd 284/
unzip frame_284.zip
rm frame_284.zip
cd ..

mkdir 285
mv frame_285_split.zip 285/
mv frame_285_split.z01 285/
cd 285/
zip frame_285_split.zip -s=0 --out frame_285.zip
unzip frame_285.zip
rm frame_285.zip
rm frame_285_split.zip
rm frame_285_split.z01
cd ..

mkdir 287
mv frame_287.zip 287/
cd 287/
unzip frame_287.zip
rm frame_287.zip
cd ..

mkdir 289
mv frame_289.zip 289/
cd 289/
unzip frame_289.zip
rm frame_289.zip
cd ..

mkdir 290
mv frame_290.zip 290/
cd 290/
unzip frame_290.zip
rm frame_290.zip
cd ..

mkdir 291
mv frame_291.zip 291/
cd 291/
unzip frame_291.zip
rm frame_291.zip
cd ..

mkdir 292
mv frame_292.zip 292/
cd 292/
unzip frame_292.zip
rm frame_292.zip
cd ..

mkdir 293
mv frame_293.zip 293/
cd 293/
unzip frame_293.zip
rm frame_293.zip
cd ..

mkdir 294
mv frame_294.zip 294/
cd 294/
unzip frame_294.zip
rm frame_294.zip
cd ..

mkdir 295
mv frame_295.zip 295/
cd 295/
unzip frame_295.zip
rm frame_295.zip
cd ..

mkdir 297
mv frame_297.zip 297/
cd 297/
unzip frame_297.zip
rm frame_297.zip
cd ..

mkdir 298
mv frame_298.zip 298/
cd 298/
unzip frame_298.zip
rm frame_298.zip
cd ..

mkdir 299
mv frame_299.zip 299/
cd 299/
unzip frame_299.zip
rm frame_299.zip
cd ..

mkdir 301
mv frame_301.zip 301/
cd 301/
unzip frame_301.zip
rm frame_301.zip
cd ..

mkdir 302
mv frame_302.zip 302/
cd 302/
unzip frame_302.zip
rm frame_302.zip
cd ..

mkdir 304
mv frame_304.zip 304/
cd 304/
unzip frame_304.zip
rm frame_304.zip
cd ..

mkdir 306
mv frame_306_split.zip 306/
mv frame_306_split.z01 306/
mv frame_306_split.z02 306/
cd 306/
zip frame_306_split.zip -s=0 --out frame_306.zip
unzip frame_306.zip
rm frame_306.zip
rm frame_306_split.zip
rm frame_306_split.z01
rm frame_306_split.z02
cd ..

mkdir 307
mv frame_307.zip 307/
cd 307/
unzip frame_307.zip
rm frame_307.zip
cd ..

mkdir 308
mv frame_308.zip 308/
cd 308/
unzip frame_308.zip
rm frame_308.zip
cd ..

mkdir 309
mv frame_309.zip 309/
cd 309/
unzip frame_309.zip
rm frame_309.zip
cd ..

mkdir 312
mv frame_312.zip 312/
cd 312/
unzip frame_312.zip
rm frame_312.zip
cd ..

mkdir 313
mv frame_313.zip 313/
cd 313/
unzip frame_313.zip
rm frame_313.zip
cd ..

mkdir 314
mv frame_314_split.zip 314/
mv frame_314_split.z01 314/
cd 314/
zip frame_314_split.zip -s=0 --out frame_314.zip
unzip frame_314.zip
rm frame_314.zip
rm frame_314_split.zip
rm frame_314_split.z01
cd ..

mkdir 315
mv frame_315.zip 315/
cd 315/
unzip frame_315.zip
rm frame_315.zip
cd ..

mkdir 316
mv frame_316.zip 316/
cd 316/
unzip frame_316.zip
rm frame_316.zip
cd ..

mkdir 317
mv frame_317.zip 317/
cd 317/
unzip frame_317.zip
rm frame_317.zip
cd ..

mkdir 318
mv frame_318.zip 318/
cd 318/
unzip frame_318.zip
rm frame_318.zip
cd ..

mkdir 320
mv frame_320.zip 320/
cd 320/
unzip frame_320.zip
rm frame_320.zip
cd ..

mkdir 321
mv frame_321.zip 321/
cd 321/
unzip frame_321.zip
rm frame_321.zip
cd ..

mkdir 323
mv frame_323.zip 323/
cd 323/
unzip frame_323.zip
rm frame_323.zip
cd ..

mkdir 324
mv frame_324.zip 324/
cd 324/
unzip frame_324.zip
rm frame_324.zip
cd ..

mkdir 325
mv frame_325.zip 325/
cd 325/
unzip frame_325.zip
rm frame_325.zip
cd ..

mkdir 327
mv frame_327.zip 327/
cd 327/
unzip frame_327.zip
rm frame_327.zip
cd ..

mkdir 328
mv frame_328.zip 328/
cd 328/
unzip frame_328.zip
rm frame_328.zip
cd ..

mkdir 329
mv frame_329.zip 329/
cd 329/
unzip frame_329.zip
rm frame_329.zip
cd ..

mkdir 330
mv frame_330.zip 330/
cd 330/
unzip frame_330.zip
rm frame_330.zip
cd ..

mkdir 331
mv frame_331.zip 331/
cd 331/
unzip frame_331.zip
rm frame_331.zip
cd ..

mkdir 334
mv frame_334.zip 334/
cd 334/
unzip frame_334.zip
rm frame_334.zip
cd ..

mkdir 335
mv frame_335.zip 335/
cd 335/
unzip frame_335.zip
rm frame_335.zip
cd ..

mkdir 338
mv frame_338.zip 338/
cd 338/
unzip frame_338.zip
rm frame_338.zip
cd ..

mkdir 339
mv frame_339.zip 339/
cd 339/
unzip frame_339.zip
rm frame_339.zip
cd ..

mkdir 340
mv frame_340.zip 340/
cd 340/
unzip frame_340.zip
rm frame_340.zip
cd ..

mkdir 341
mv frame_341.zip 341/
cd 341/
unzip frame_341.zip
rm frame_341.zip
cd ..

mkdir 342
mv frame_342.zip 342/
cd 342/
unzip frame_342.zip
rm frame_342.zip
cd ..

mkdir 343
mv frame_343.zip 343/
cd 343/
unzip frame_343.zip
rm frame_343.zip
cd ..

mkdir 344
mv frame_344.zip 344/
cd 344/
unzip frame_344.zip
rm frame_344.zip
cd ..

mkdir 345
mv frame_345.zip 345/
cd 345/
unzip frame_345.zip
rm frame_345.zip
cd ..

mkdir 346
mv frame_346.zip 346/
cd 346/
unzip frame_346.zip
rm frame_346.zip
cd ..

mkdir 347
mv frame_347.zip 347/
cd 347/
unzip frame_347.zip
rm frame_347.zip
cd ..

mkdir 348
mv frame_348.zip 348/
cd 348/
unzip frame_348.zip
rm frame_348.zip
cd ..

mkdir 352
mv frame_352.zip 352/
cd 352/
unzip frame_352.zip
rm frame_352.zip
cd ..

mkdir 353
mv frame_353.zip 353/
cd 353/
unzip frame_353.zip
rm frame_353.zip
cd ..

mkdir 354
mv frame_354.zip 354/
cd 354/
unzip frame_354.zip
rm frame_354.zip
cd ..

mkdir 355
mv frame_355.zip 355/
cd 355/
unzip frame_355.zip
rm frame_355.zip
cd ..

mkdir 360
mv frame_360.zip 360/
cd 360/
unzip frame_360.zip
rm frame_360.zip
cd ..

mkdir 361
mv frame_361.zip 361/
cd 361/
unzip frame_361.zip
rm frame_361.zip
cd ..

mkdir 363
mv frame_363.zip 363/
cd 363/
unzip frame_363.zip
rm frame_363.zip
cd ..

mkdir 364
mv frame_364_split.zip 364/
mv frame_364_split.z01 364/
mv frame_364_split.z02 364/
mv frame_364_split.z03 364/
cd 364/
zip frame_364_split.zip -s=0 --out frame_364.zip
unzip frame_364.zip
rm frame_364.zip
rm frame_364_split.zip
rm frame_364_split.z01
rm frame_364_split.z02
rm frame_364_split.z03
cd ..

mkdir 365
mv frame_365_split.zip 365/
mv frame_365_split.z01 365/
mv frame_365_split.z02 365/
cd 365/
zip frame_365_split.zip -s=0 --out frame_365.zip
unzip frame_365.zip
rm frame_365.zip
rm frame_365_split.zip
rm frame_365_split.z01
rm frame_365_split.z02
cd ..

mkdir 368
mv frame_368.zip 368/
cd 368/
unzip frame_368.zip
rm frame_368.zip
cd ..

mkdir 369
mv frame_369.zip 369/
cd 369/
unzip frame_369.zip
rm frame_369.zip
cd ..

mkdir 370
mv frame_370.zip 370/
cd 370/
unzip frame_370.zip
rm frame_370.zip
cd ..

mkdir 371
mv frame_371.zip 371/
cd 371/
unzip frame_371.zip
rm frame_371.zip
cd ..

mkdir 372
mv frame_372.zip 372/
cd 372/
unzip frame_372.zip
rm frame_372.zip
cd ..

mkdir 374
mv frame_374.zip 374/
cd 374/
unzip frame_374.zip
rm frame_374.zip
cd ..

mkdir 375
mv frame_375_split.zip 375/
mv frame_375_split.z01 375/
cd 375/
zip frame_375_split.zip -s=0 --out frame_375.zip
unzip frame_375.zip
rm frame_375.zip
rm frame_375_split.zip
rm frame_375_split.z01
cd ..

mkdir 376
mv frame_376.zip 376/
cd 376/
unzip frame_376.zip
rm frame_376.zip
cd ..

mkdir 377
mv frame_377.zip 377/
cd 377/
unzip frame_377.zip
rm frame_377.zip
cd ..

mkdir 378
mv frame_378.zip 378/
cd 378/
unzip frame_378.zip
rm frame_378.zip
cd ..

mkdir 379
mv frame_379.zip 379/
cd 379/
unzip frame_379.zip
rm frame_379.zip
cd ..

mkdir 380
mv frame_380.zip 380/
cd 380/
unzip frame_380.zip
rm frame_380.zip
cd ..

mkdir 381
mv frame_381.zip 381/
cd 381/
unzip frame_381.zip
rm frame_381.zip
cd ..

mkdir 382
mv frame_382.zip 382/
cd 382/
unzip frame_382.zip
rm frame_382.zip
cd ..

mkdir 384
mv frame_384.zip 384/
cd 384/
unzip frame_384.zip
rm frame_384.zip
cd ..

mkdir 385
mv frame_385.zip 385/
cd 385/
unzip frame_385.zip
rm frame_385.zip
cd ..

mkdir 386
mv frame_386.zip 386/
cd 386/
unzip frame_386.zip
rm frame_386.zip
cd ..

mkdir 387
mv frame_387.zip 387/
cd 387/
unzip frame_387.zip
rm frame_387.zip
cd ..

mkdir 388
mv frame_388.zip 388/
cd 388/
unzip frame_388.zip
rm frame_388.zip
cd ..

mkdir 389
mv frame_389.zip 389/
cd 389/
unzip frame_389.zip
rm frame_389.zip
cd ..

mkdir 390
mv frame_390.zip 390/
cd 390/
unzip frame_390.zip
rm frame_390.zip
cd ..

mkdir 393
mv frame_393.zip 393/
cd 393/
unzip frame_393.zip
rm frame_393.zip
cd ..

mkdir 394
mv frame_394.zip 394/
cd 394/
unzip frame_394.zip
rm frame_394.zip
cd ..

mkdir 395
mv frame_395.zip 395/
cd 395/
unzip frame_395.zip
rm frame_395.zip
cd ..

mkdir 396
mv frame_396.zip 396/
cd 396/
unzip frame_396.zip
rm frame_396.zip
cd ..

mkdir 398
mv frame_398.zip 398/
cd 398/
unzip frame_398.zip
rm frame_398.zip
cd ..

mkdir 399
mv frame_399.zip 399/
cd 399/
unzip frame_399.zip
rm frame_399.zip
cd ..

mkdir 402
mv frame_402.zip 402/
cd 402/
unzip frame_402.zip
rm frame_402.zip
cd ..

mkdir 403
mv frame_403.zip 403/
cd 403/
unzip frame_403.zip
rm frame_403.zip
cd ..

mkdir 405
mv frame_405.zip 405/
cd 405/
unzip frame_405.zip
rm frame_405.zip
cd ..

mkdir 407
mv frame_407.zip 407/
cd 407/
unzip frame_407.zip
rm frame_407.zip
cd ..

mkdir 409
mv frame_409.zip 409/
cd 409/
unzip frame_409.zip
rm frame_409.zip
cd ..

mkdir 411
mv frame_411.zip 411/
cd 411/
unzip frame_411.zip
rm frame_411.zip
cd ..

mkdir 412
mv frame_412.zip 412/
cd 412/
unzip frame_412.zip
rm frame_412.zip
cd ..

mkdir 413
mv frame_413.zip 413/
cd 413/
unzip frame_413.zip
rm frame_413.zip
cd ..

mkdir 414
mv frame_414.zip 414/
cd 414/
unzip frame_414.zip
rm frame_414.zip
cd ..

mkdir 415
mv frame_415_split.zip 415/
mv frame_415_split.z01 415/
cd 415/
zip frame_415_split.zip -s=0 --out frame_415.zip
unzip frame_415.zip
rm frame_415.zip
rm frame_415_split.zip
rm frame_415_split.z01
cd ..

mkdir 416
mv frame_416.zip 416/
cd 416/
unzip frame_416.zip
rm frame_416.zip
cd ..

mkdir 417
mv frame_417_split.zip 417/
mv frame_417_split.z01 417/
cd 417/
zip frame_417_split.zip -s=0 --out frame_417.zip
unzip frame_417.zip
rm frame_417.zip
rm frame_417_split.zip
rm frame_417_split.z01
cd ..

mkdir 419
mv frame_419.zip 419/
cd 419/
unzip frame_419.zip
rm frame_419.zip
cd ..

mkdir 420
mv frame_420.zip 420/
cd 420/
unzip frame_420.zip
rm frame_420.zip
cd ..

mkdir 421
mv frame_421.zip 421/
cd 421/
unzip frame_421.zip
rm frame_421.zip
cd ..

mkdir 422
mv frame_422.zip 422/
cd 422/
unzip frame_422.zip
rm frame_422.zip
cd ..

mkdir 423
mv frame_423.zip 423/
cd 423/
unzip frame_423.zip
rm frame_423.zip
cd ..

mkdir 424
mv frame_424.zip 424/
cd 424/
unzip frame_424.zip
rm frame_424.zip
cd ..

mkdir 425
mv frame_425_split.zip 425/
mv frame_425_split.z01 425/
mv frame_425_split.z02 425/
cd 425/
zip frame_425_split.zip -s=0 --out frame_425.zip
unzip frame_425.zip
rm frame_425.zip
rm frame_425_split.zip
rm frame_425_split.z01
rm frame_425_split.z02
cd ..

mkdir 426
mv frame_426_split.zip 426/
mv frame_426_split.z01 426/
cd 426/
zip frame_426_split.zip -s=0 --out frame_426.zip
unzip frame_426.zip
rm frame_426.zip
rm frame_426_split.zip
rm frame_426_split.z01
cd ..

mkdir 428
mv frame_428.zip 428/
cd 428/
unzip frame_428.zip
rm frame_428.zip
cd ..

mkdir 429
mv frame_429.zip 429/
cd 429/
unzip frame_429.zip
rm frame_429.zip
cd ..

mkdir 430
mv frame_430.zip 430/
cd 430/
unzip frame_430.zip
rm frame_430.zip
cd ..

mkdir 431
mv frame_431.zip 431/
cd 431/
unzip frame_431.zip
rm frame_431.zip
cd ..

mkdir 432
mv frame_432.zip 432/
cd 432/
unzip frame_432.zip
rm frame_432.zip
cd ..

mkdir 433
mv frame_433.zip 433/
cd 433/
unzip frame_433.zip
rm frame_433.zip
cd ..

mkdir 434
mv frame_434.zip 434/
cd 434/
unzip frame_434.zip
rm frame_434.zip
cd ..

mkdir 435
mv frame_435.zip 435/
cd 435/
unzip frame_435.zip
rm frame_435.zip
cd ..

mkdir 438
mv frame_438.zip 438/
cd 438/
unzip frame_438.zip
rm frame_438.zip
cd ..

mkdir 439
mv frame_439.zip 439/
cd 439/
unzip frame_439.zip
rm frame_439.zip
cd ..

mkdir 440
mv frame_440_split.zip 440/
mv frame_440_split.z01 440/
mv frame_440_split.z02 440/
cd 440/
zip frame_440_split.zip -s=0 --out frame_440.zip
unzip frame_440.zip
rm frame_440.zip
rm frame_440_split.zip
rm frame_440_split.z01
rm frame_440_split.z02
cd ..

mkdir 441
mv frame_441.zip 441/
cd 441/
unzip frame_441.zip
rm frame_441.zip
cd ..

mkdir 442
mv frame_442.zip 442/
cd 442/
unzip frame_442.zip
rm frame_442.zip
cd ..

mkdir 443
mv frame_443.zip 443/
cd 443/
unzip frame_443.zip
rm frame_443.zip
cd ..

mkdir 444
mv frame_444.zip 444/
cd 444/
unzip frame_444.zip
rm frame_444.zip
cd ..

mkdir 445
mv frame_445.zip 445/
cd 445/
unzip frame_445.zip
rm frame_445.zip
cd ..

mkdir 448
mv frame_448.zip 448/
cd 448/
unzip frame_448.zip
rm frame_448.zip
cd ..

mkdir 450
mv frame_450.zip 450/
cd 450/
unzip frame_450.zip
rm frame_450.zip
cd ..

mkdir 451
mv frame_451.zip 451/
cd 451/
unzip frame_451.zip
rm frame_451.zip
cd ..

mkdir 452
mv frame_452.zip 452/
cd 452/
unzip frame_452.zip
rm frame_452.zip
cd ..

mkdir 454
mv frame_454.zip 454/
cd 454/
unzip frame_454.zip
rm frame_454.zip
cd ..

mkdir 455
mv frame_455_split.zip 455/
mv frame_455_split.z01 455/
cd 455/
zip frame_455_split.zip -s=0 --out frame_455.zip
unzip frame_455.zip
rm frame_455.zip
rm frame_455_split.zip
rm frame_455_split.z01
cd ..

mkdir 458
mv frame_458_split.zip 458/
mv frame_458_split.z01 458/
mv frame_458_split.z02 458/
cd 458/
zip frame_458_split.zip -s=0 --out frame_458.zip
unzip frame_458.zip
rm frame_458.zip
rm frame_458_split.zip
rm frame_458_split.z01
rm frame_458_split.z02
cd ..

mkdir 462
mv frame_462_split.zip 462/
mv frame_462_split.z01 462/
mv frame_462_split.z02 462/
mv frame_462_split.z03 462/
cd 462/
zip frame_462_split.zip -s=0 --out frame_462.zip
unzip frame_462.zip
rm frame_462.zip
rm frame_462_split.zip
rm frame_462_split.z01
rm frame_462_split.z02
rm frame_462_split.z03
cd ..

mkdir 463
mv frame_463.zip 463/
cd 463/
unzip frame_463.zip
rm frame_463.zip
cd ..

mkdir 466
mv frame_466.zip 466/
cd 466/
unzip frame_466.zip
rm frame_466.zip
cd ..

mkdir 467
mv frame_467.zip 467/
cd 467/
unzip frame_467.zip
rm frame_467.zip
cd ..

mkdir 468
mv frame_468.zip 468/
cd 468/
unzip frame_468.zip
rm frame_468.zip
cd ..

mkdir 471
mv frame_471.zip 471/
cd 471/
unzip frame_471.zip
rm frame_471.zip
cd ..

mkdir 473
mv frame_473_split.zip 473/
mv frame_473_split.z01 473/
cd 473/
zip frame_473_split.zip -s=0 --out frame_473.zip
unzip frame_473.zip
rm frame_473.zip
rm frame_473_split.zip
rm frame_473_split.z01
cd ..

mkdir 474
mv frame_474.zip 474/
cd 474/
unzip frame_474.zip
rm frame_474.zip
cd ..

mkdir 475
mv frame_475.zip 475/
cd 475/
unzip frame_475.zip
rm frame_475.zip
cd ..

mkdir 476
mv frame_476.zip 476/
cd 476/
unzip frame_476.zip
rm frame_476.zip
cd ..

mkdir 477
mv frame_477.zip 477/
cd 477/
unzip frame_477.zip
rm frame_477.zip
cd ..

mkdir 478
mv frame_478.zip 478/
cd 478/
unzip frame_478.zip
rm frame_478.zip
cd ..

mkdir 479
mv frame_479.zip 479/
cd 479/
unzip frame_479.zip
rm frame_479.zip
cd ..

mkdir 480
mv frame_480.zip 480/
cd 480/
unzip frame_480.zip
rm frame_480.zip
cd ..

mkdir 483
mv frame_483.zip 483/
cd 483/
unzip frame_483.zip
rm frame_483.zip
cd ..

mkdir 484
mv frame_484.zip 484/
cd 484/
unzip frame_484.zip
rm frame_484.zip
cd ..

mkdir 485
mv frame_485_split.zip 485/
mv frame_485_split.z01 485/
mv frame_485_split.z02 485/
cd 485/
zip frame_485_split.zip -s=0 --out frame_485.zip
unzip frame_485.zip
rm frame_485.zip
rm frame_485_split.zip
rm frame_485_split.z01
rm frame_485_split.z02
cd ..

mkdir 487
mv frame_487_split.zip 487/
mv frame_487_split.z01 487/
mv frame_487_split.z02 487/
cd 487/
zip frame_487_split.zip -s=0 --out frame_487.zip
unzip frame_487.zip
rm frame_487.zip
rm frame_487_split.zip
rm frame_487_split.z01
rm frame_487_split.z02
cd ..

mkdir 488
mv frame_488.zip 488/
cd 488/
unzip frame_488.zip
rm frame_488.zip
cd ..

mkdir 489
mv frame_489.zip 489/
cd 489/
unzip frame_489.zip
rm frame_489.zip
cd ..

mkdir 490
mv frame_490_split.zip 490/
mv frame_490_split.z01 490/
cd 490/
zip frame_490_split.zip -s=0 --out frame_490.zip
unzip frame_490.zip
rm frame_490.zip
rm frame_490_split.zip
rm frame_490_split.z01
cd ..

mkdir 491
mv frame_491.zip 491/
cd 491/
unzip frame_491.zip
rm frame_491.zip
cd ..

mkdir 492
mv frame_492.zip 492/
cd 492/
unzip frame_492.zip
rm frame_492.zip
cd ..

mkdir 494
mv frame_494.zip 494/
cd 494/
unzip frame_494.zip
rm frame_494.zip
cd ..

mkdir 495
mv frame_495.zip 495/
cd 495/
unzip frame_495.zip
rm frame_495.zip
cd ..

mkdir 497
mv frame_497.zip 497/
cd 497/
unzip frame_497.zip
rm frame_497.zip
cd ..

mkdir 499
mv frame_499.zip 499/
cd 499/
unzip frame_499.zip
rm frame_499.zip
cd ..
