#!/bin/bash

mkdir 005
mv frame_005_split.zip 005/
mv frame_005_split.z01 005/
mv frame_005_split.z02 005/
cd 005/
zip frame_005_split.zip -s=0 --out frame_005.zip
unzip frame_005.zip
rm frame_005.zip
rm frame_005_split.zip
rm frame_005_split.z01
rm frame_005_split.z02
cd ..

mkdir 008
mv frame_008.zip 008/
cd 008/
unzip frame_008.zip
rm frame_008.zip
cd ..

mkdir 009
mv frame_009.zip 009/
cd 009/
unzip frame_009.zip
rm frame_009.zip
cd ..

mkdir 015
mv frame_015.zip 015/
cd 015/
unzip frame_015.zip
rm frame_015.zip
cd ..

mkdir 029
mv frame_029.zip 029/
cd 029/
unzip frame_029.zip
rm frame_029.zip
cd ..

mkdir 033
mv frame_033.zip 033/
cd 033/
unzip frame_033.zip
rm frame_033.zip
cd ..

mkdir 041
mv frame_041_split.zip 041/
mv frame_041_split.z01 041/
mv frame_041_split.z02 041/
cd 041/
zip frame_041_split.zip -s=0 --out frame_041.zip
unzip frame_041.zip
rm frame_041.zip
rm frame_041_split.zip
rm frame_041_split.z01
rm frame_041_split.z02
cd ..

mkdir 042
mv frame_042.zip 042/
cd 042/
unzip frame_042.zip
rm frame_042.zip
cd ..

mkdir 086
mv frame_086.zip 086/
cd 086/
unzip frame_086.zip
rm frame_086.zip
cd ..

mkdir 095
mv frame_095.zip 095/
cd 095/
unzip frame_095.zip
rm frame_095.zip
cd ..

mkdir 102
mv frame_102.zip 102/
cd 102/
unzip frame_102.zip
rm frame_102.zip
cd ..

mkdir 115
mv frame_115_split.zip 115/
mv frame_115_split.z01 115/
cd 115/
zip frame_115_split.zip -s=0 --out frame_115.zip
unzip frame_115.zip
rm frame_115.zip
rm frame_115_split.zip
rm frame_115_split.z01
cd ..

mkdir 124
mv frame_124_split.zip 124/
mv frame_124_split.z01 124/
mv frame_124_split.z02 124/
cd 124/
zip frame_124_split.zip -s=0 --out frame_124.zip
unzip frame_124.zip
rm frame_124.zip
rm frame_124_split.zip
rm frame_124_split.z01
rm frame_124_split.z02
cd ..

mkdir 141
mv frame_141.zip 141/
cd 141/
unzip frame_141.zip
rm frame_141.zip
cd ..

mkdir 144
mv frame_144.zip 144/
cd 144/
unzip frame_144.zip
rm frame_144.zip
cd ..

mkdir 156
mv frame_156.zip 156/
cd 156/
unzip frame_156.zip
rm frame_156.zip
cd ..

mkdir 157
mv frame_157_split.zip 157/
mv frame_157_split.z01 157/
cd 157/
zip frame_157_split.zip -s=0 --out frame_157.zip
unzip frame_157.zip
rm frame_157.zip
rm frame_157_split.zip
rm frame_157_split.z01
cd ..

mkdir 159
mv frame_159_split.zip 159/
mv frame_159_split.z01 159/
mv frame_159_split.z02 159/
cd 159/
zip frame_159_split.zip -s=0 --out frame_159.zip
unzip frame_159.zip
rm frame_159.zip
rm frame_159_split.zip
rm frame_159_split.z01
rm frame_159_split.z02
cd ..

mkdir 166
mv frame_166_split.zip 166/
mv frame_166_split.z01 166/
cd 166/
zip frame_166_split.zip -s=0 --out frame_166.zip
unzip frame_166.zip
rm frame_166.zip
rm frame_166_split.zip
rm frame_166_split.z01
cd ..

mkdir 172
mv frame_172.zip 172/
cd 172/
unzip frame_172.zip
rm frame_172.zip
cd ..

mkdir 188
mv frame_188_split.zip 188/
mv frame_188_split.z01 188/
cd 188/
zip frame_188_split.zip -s=0 --out frame_188.zip
unzip frame_188.zip
rm frame_188.zip
rm frame_188_split.zip
rm frame_188_split.z01
cd ..

mkdir 190
mv frame_190_split.zip 190/
mv frame_190_split.z01 190/
cd 190/
zip frame_190_split.zip -s=0 --out frame_190.zip
unzip frame_190.zip
rm frame_190.zip
rm frame_190_split.zip
rm frame_190_split.z01
cd ..

mkdir 204
mv frame_204.zip 204/
cd 204/
unzip frame_204.zip
rm frame_204.zip
cd ..

mkdir 209
mv frame_209_split.zip 209/
mv frame_209_split.z01 209/
mv frame_209_split.z02 209/
cd 209/
zip frame_209_split.zip -s=0 --out frame_209.zip
unzip frame_209.zip
rm frame_209.zip
rm frame_209_split.zip
rm frame_209_split.z01
rm frame_209_split.z02
cd ..

mkdir 226
mv frame_226.zip 226/
cd 226/
unzip frame_226.zip
rm frame_226.zip
cd ..

mkdir 244
mv frame_244.zip 244/
cd 244/
unzip frame_244.zip
rm frame_244.zip
cd ..

mkdir 258
mv frame_258.zip 258/
cd 258/
unzip frame_258.zip
rm frame_258.zip
cd ..

mkdir 259
mv frame_259.zip 259/
cd 259/
unzip frame_259.zip
rm frame_259.zip
cd ..

mkdir 273
mv frame_273.zip 273/
cd 273/
unzip frame_273.zip
rm frame_273.zip
cd ..

mkdir 274
mv frame_274.zip 274/
cd 274/
unzip frame_274.zip
rm frame_274.zip
cd ..

mkdir 305
mv frame_305.zip 305/
cd 305/
unzip frame_305.zip
rm frame_305.zip
cd ..

mkdir 310
mv frame_310.zip 310/
cd 310/
unzip frame_310.zip
rm frame_310.zip
cd ..

mkdir 326
mv frame_326.zip 326/
cd 326/
unzip frame_326.zip
rm frame_326.zip
cd ..

mkdir 332
mv frame_332.zip 332/
cd 332/
unzip frame_332.zip
rm frame_332.zip
cd ..

mkdir 336
mv frame_336.zip 336/
cd 336/
unzip frame_336.zip
rm frame_336.zip
cd ..

mkdir 349
mv frame_349.zip 349/
cd 349/
unzip frame_349.zip
rm frame_349.zip
cd ..

mkdir 350
mv frame_350.zip 350/
cd 350/
unzip frame_350.zip
rm frame_350.zip
cd ..

mkdir 362
mv frame_362.zip 362/
cd 362/
unzip frame_362.zip
rm frame_362.zip
cd ..

mkdir 373
mv frame_373.zip 373/
cd 373/
unzip frame_373.zip
rm frame_373.zip
cd ..

mkdir 392
mv frame_392.zip 392/
cd 392/
unzip frame_392.zip
rm frame_392.zip
cd ..

mkdir 400
mv frame_400.zip 400/
cd 400/
unzip frame_400.zip
rm frame_400.zip
cd ..

mkdir 401
mv frame_401.zip 401/
cd 401/
unzip frame_401.zip
rm frame_401.zip
cd ..

mkdir 436
mv frame_436.zip 436/
cd 436/
unzip frame_436.zip
rm frame_436.zip
cd ..

mkdir 446
mv frame_446.zip 446/
cd 446/
unzip frame_446.zip
rm frame_446.zip
cd ..

mkdir 456
mv frame_456.zip 456/
cd 456/
unzip frame_456.zip
rm frame_456.zip
cd ..

mkdir 457
mv frame_457.zip 457/
cd 457/
unzip frame_457.zip
rm frame_457.zip
cd ..

mkdir 464
mv frame_464_split.zip 464/
mv frame_464_split.z01 464/
cd 464/
zip frame_464_split.zip -s=0 --out frame_464.zip
unzip frame_464.zip
rm frame_464.zip
rm frame_464_split.zip
rm frame_464_split.z01
cd ..

mkdir 482
mv frame_482_split.zip 482/
mv frame_482_split.z01 482/
cd 482/
zip frame_482_split.zip -s=0 --out frame_482.zip
unzip frame_482.zip
rm frame_482.zip
rm frame_482_split.zip
rm frame_482_split.z01
cd ..

mkdir 486
mv frame_486.zip 486/
cd 486/
unzip frame_486.zip
rm frame_486.zip
cd ..

mkdir 493
mv frame_493_split.zip 493/
mv frame_493_split.z01 493/
cd 493/
zip frame_493_split.zip -s=0 --out frame_493.zip
unzip frame_493.zip
rm frame_493.zip
rm frame_493_split.zip
rm frame_493_split.z01
cd ..
